apiVersion: apps/v1
kind: Deployment
metadata:
  name: eyego-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eyego-zookeeper
  template:
    metadata:
      labels:
        app: eyego-zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.5.0
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        ports:
        - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: eyego-zookeeper
spec:
  ports:
    - port: 2181
  selector:
    app: eyego-zookeeper